networks:
  vpn-network:
    driver: bridge

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qbittorrent
      - 8000:8000/tcp # Gluetun WebUI
    networks:
      - vpn-network
    volumes:
      - {{DOCKERCONFDIR}}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn #https://www.youtube.com/watch?v=SQEqsaKN-Go&t=271s
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY={{WIREGUARD_PRIVATE_KEY}}
      - WIREGUARD_PRESHARED_KEY={{WIREGUARD_PRESHARED_KEY}}
      - WIREGUARD_ADDRESSES={{WIREGUARD_ADDRESSES}}
      - FIREWALL_VPN_INPUT_PORTS={{FIREWALL_VPN_INPUT_PORTS}}
      - SERVER_COUNTRIES={{SERVER_COUNTRIES}}
      - UPDATER_PERIOD=24h
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    networks:
      - vpn-network
    ports:
      - 8191:8191
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - LOG_LEVEL=info
      # Recommended settings for better stability
      - CAPTCHA_SOLVER=none
      - MAX_TIMEOUT=60000
      - BROWSER_TIMEOUT=40000
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    network_mode: "service:gluetun"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - WEBUI_PORTS=8080/tcp,8080/udp
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/qbittorrent:/config
      - {{DOCKERSTORAGEDIR}}/torrents:/data/torrents:rw
    depends_on:
      - gluetun

  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd
    networks:
      - vpn-network
    ports:
      - 8282:8282
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - WEBUI_PORTS=8282/tcp,8282/udp
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/sabnzbd:/config
      - {{DOCKERSTORAGEDIR}}/usenet:/data/usenet:rw

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    networks:
      - vpn-network
    ports:
      - 9696:9696
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    restart: unless-stopped
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/prowlarr:/config:rw
    depends_on:
      - flaresolverr

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    networks:
      - vpn-network
    ports:
      - 7878:7878
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    restart: unless-stopped
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/radarr:/config
      - {{DOCKERSTORAGEDIR}}:/data
    depends_on:
      - prowlarr
      - qbittorrent
      - sabnzbd

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    networks:
      - vpn-network
    ports:
      - 8989:8989
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    restart: unless-stopped
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/sonarr:/config
      - {{DOCKERSTORAGEDIR}}:/data
    depends_on:
      - prowlarr
      - qbittorrent
      - sabnzbd

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:nightly
    networks:
      - vpn-network
    ports:
      - 6767:6767
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    restart: unless-stopped
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/bazarr:/config
      - {{DOCKERSTORAGEDIR}}/media:/data/media
    depends_on:
      - sonarr
      - radarr

  emby:
    container_name: emby
    image: lscr.io/linuxserver/emby
    networks:
      - vpn-network
    ports:
      - 8096:8096
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/emby:/config:rw
      - {{DOCKERSTORAGEDIR}}/media:/data/media:rw
    devices:
      - /dev/dri:/dev/dri # optional: if you have a Synology with an Intel CPU and want hardware transcoding

  jellyseerr:
    container_name: jellyseerr
    image: hotio/jellyseerr
    networks:
      - vpn-network
    ports:
      - 5055:5055
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: {{DOCKERLOGGING_MAXFILE}}
        max-size: {{DOCKERLOGGING_MAXSIZE}}
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ={{TZ}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/jellyseerr:/config
      - {{DOCKERSTORAGEDIR}}/media:/data/media
    depends_on:
      - emby

  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    networks:
      - vpn-network
    user: {{PUID}}:{{PGID}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{DOCKERCONFDIR}}/recyclarr:/config
    environment:
      - TZ={{TZ}}
    depends_on:
      - radarr
      - sonarr

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    networks:
      - vpn-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ={{TZ}}
      - WATCHTOWER_SCHEDULE={{WATCHTOWER_SCHEDULE}}
      - WATCHTOWER_NOTIFICATION_URL={{WATCHTOWER_NOTIFICATION_URL}}
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_TIMEOUT=30s