---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Luda's Homepage

background:
  image: https://images.pexels.com/photos/7509250/pexels-photo-7509250.jpeg?cs=srgb&dl=pexels-gra-wal-38714864-7509250.jpg&fm=jpg&w=6000&h=4000
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 90

theme: dark
color: neutral

useEqualHeights: true

headerStyle: underlined

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom

layout:
  Router & DNS:
    header: true
    style: row
    columns: 2
  Hypervisor & Storage:
    header: true
    style: row
    columns: 2
  Arr Stack:
    header: true
    style: row
    columns: 4
  Media:
    header: true
    style: row
    columns: 2
  Utilities:
    header: true
    style: row
    columns: 2
  Other:
    header: true
    style: row
    columns: 4

hideVersion: true
showStats: true